BEGIN;

INSERT INTO prestamos.estados_prestamo(nombre)
SELECT 'RENEGOCIADO'
WHERE NOT EXISTS (SELECT 1 FROM prestamos.estados_prestamo WHERE nombre='RENEGOCIADO');

INSERT INTO prestamos.estados_prestamo(nombre)
SELECT 'REENGANCHADO'
WHERE NOT EXISTS (SELECT 1 FROM prestamos.estados_prestamo WHERE nombre='REENGANCHADO');

ALTER TABLE prestamos.prestamos
  ADD COLUMN IF NOT EXISTS id_prestamo_origen integer,
  ADD COLUMN IF NOT EXISTS monto_descontado numeric(12,2),
  ADD COLUMN IF NOT EXISTS monto_entregado numeric(12,2);

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='fk_prestamo_origen') THEN
    ALTER TABLE prestamos.prestamos
      ADD CONSTRAINT fk_prestamo_origen
      FOREIGN KEY(id_prestamo_origen) REFERENCES prestamos.prestamos(id_prestamo);
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS prestamos.reenganches_san(
  id_reenganche integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_prestamo_anterior integer NOT NULL REFERENCES prestamos.prestamos(id_prestamo),
  id_prestamo_nuevo integer NOT NULL REFERENCES prestamos.prestamos(id_prestamo),
  saldo_cancelado numeric(12,2) NOT NULL,
  monto_nuevo numeric(12,2) NOT NULL,
  monto_entregado numeric(12,2) NOT NULL,
  fecha_operacion date NOT NULL,
  observacion text,
  fecha_registro timestamp without time zone NOT NULL DEFAULT current_timestamp,
  UNIQUE(id_prestamo_anterior),
  UNIQUE(id_prestamo_nuevo)
);

UPDATE prestamos.prestamos p
SET id_prestamo_origen=r.id_prestamo_anterior,
    monto_descontado=r.saldo_cancelado,
    monto_entregado=r.monto_entregado
FROM prestamos.reenganches_san r
WHERE p.id_prestamo=r.id_prestamo_nuevo
  AND (p.id_prestamo_origen IS DISTINCT FROM r.id_prestamo_anterior
    OR p.monto_descontado IS DISTINCT FROM r.saldo_cancelado
    OR p.monto_entregado IS DISTINCT FROM r.monto_entregado);

DROP FUNCTION IF EXISTS prestamos.crear_reenganche_san(integer,numeric,numeric,integer,character varying,date,text);

CREATE FUNCTION prestamos.crear_reenganche_san(
  p_id_prestamo_origen integer,
  p_monto_nuevo numeric,
  p_cuota numeric,
  p_cantidad_periodos integer,
  p_frecuencia varchar,
  p_fecha_inicio date,
  p_observacion text DEFAULT NULL
) RETURNS integer LANGUAGE plpgsql AS $$
DECLARE
  v_id_cliente integer;
  v_tipo varchar;
  v_estado varchar;
  v_saldo numeric(12,2);
  v_id_nuevo integer;
  v_id_renegociado integer;
BEGIN
  IF p_monto_nuevo<=0 OR p_cuota<=0 OR p_cantidad_periodos<=0 THEN
    RAISE EXCEPTION 'El monto, la cuota y la cantidad de periodos deben ser mayores que cero.';
  END IF;

  SELECT p.id_cliente,tp.nombre,ep.nombre
  INTO v_id_cliente,v_tipo,v_estado
  FROM prestamos.prestamos p
  JOIN prestamos.tipos_prestamo tp ON tp.id_tipo_prestamos=p.id_tipo_prestamos
  JOIN prestamos.estados_prestamo ep ON ep.id_estado_prestamo=p.id_estado_prestamo
  WHERE p.id_prestamo=p_id_prestamo_origen
  FOR UPDATE OF p;

  IF v_id_cliente IS NULL THEN RAISE EXCEPTION 'El prestamo de origen no existe.'; END IF;
  IF v_tipo<>'SAN' THEN RAISE EXCEPTION 'El reenganche solo aplica a prestamos SAN.'; END IF;
  IF v_estado<>'ACTIVO' THEN RAISE EXCEPTION 'El prestamo de origen debe estar activo.'; END IF;

  SELECT COALESCE(SUM(GREATEST(monto_programado-COALESCE(monto_pagado,0),0)),0)
  INTO v_saldo
  FROM prestamos.plan_pagos
  WHERE id_prestamo=p_id_prestamo_origen;

  IF v_saldo<=0 THEN RAISE EXCEPTION 'El prestamo no tiene saldo pendiente.'; END IF;
  IF p_monto_nuevo<=v_saldo THEN
    RAISE EXCEPTION 'El nuevo monto debe ser mayor que el saldo pendiente de RD$%.',v_saldo;
  END IF;

  v_id_nuevo:=prestamos.crear_prestamo_san(
    v_id_cliente,p_monto_nuevo,p_cuota,p_cantidad_periodos,
    p_frecuencia,p_fecha_inicio,p_observacion
  );

  UPDATE prestamos.prestamos
  SET id_prestamo_origen=p_id_prestamo_origen,
      monto_descontado=v_saldo,
      monto_entregado=p_monto_nuevo-v_saldo
  WHERE id_prestamo=v_id_nuevo;

  SELECT id_estado_prestamo INTO v_id_renegociado
  FROM prestamos.estados_prestamo WHERE nombre='RENEGOCIADO';

  UPDATE prestamos.prestamos
  SET id_estado_prestamo=v_id_renegociado
  WHERE id_prestamo=p_id_prestamo_origen;

  UPDATE prestamos.plan_pagos
  SET estado='REENGANCHADO'
  WHERE id_prestamo=p_id_prestamo_origen
    AND monto_pagado<monto_programado;

  INSERT INTO prestamos.reenganches_san(
    id_prestamo_anterior,id_prestamo_nuevo,saldo_cancelado,
    monto_nuevo,monto_entregado,fecha_operacion,observacion
  ) VALUES(
    p_id_prestamo_origen,v_id_nuevo,v_saldo,
    p_monto_nuevo,p_monto_nuevo-v_saldo,p_fecha_inicio,p_observacion
  );

  INSERT INTO prestamos.historial_prestamos(id_prestamo,accion,descripcion)
  VALUES
    (p_id_prestamo_origen,'REENGANCHE_APLICADO','Saldo de RD$'||v_saldo||' absorbido por el prestamo #'||v_id_nuevo||'.'),
    (v_id_nuevo,'REENGANCHE_CREADO','Reenganche del prestamo #'||p_id_prestamo_origen||'. Efectivo entregado: RD$'||(p_monto_nuevo-v_saldo)||'.');

  RETURN v_id_nuevo;
END;
$$;

COMMIT;
