using Npgsql;
namespace SistemaPrestamos.Api.Services;
public sealed record CajaDetalleDto(string TipoPago,long Cantidad,decimal Total);
public sealed record CajaMovimientoDto(int PagoId,int PrestamoId,string Cliente,string TipoPago,decimal Monto,string Estado,string? Recibo);
public sealed record CajaDiaDto(int? Id,DateOnly Fecha,bool Cerrada,decimal TotalSistema,decimal? TotalDeclarado,decimal? Diferencia,long CantidadPagos,long CantidadAnulados,string? Observacion,string? Usuario,DateTime? FechaRegistro,List<CajaDetalleDto> Detalle,List<CajaMovimientoDto> Movimientos);
public sealed record CerrarCajaRequest(DateOnly Fecha,decimal TotalDeclarado,string? Observacion);
public sealed record CierreCajaListaDto(int Id,DateOnly Fecha,decimal TotalSistema,decimal TotalDeclarado,decimal Diferencia,int CantidadPagos,int CantidadAnulados,string Usuario,DateTime FechaRegistro);
public sealed class CierreCajaRepository(NpgsqlDataSource source)
{
 public async Task<CajaDiaDto> DiaAsync(DateOnly fecha)
 {
  int? id=null;decimal total=0;decimal? declared=null,difference=null;long payments=0,annulled=0;string? note=null,user=null;DateTime? created=null;
  await using(var c=source.CreateCommand("SELECT id_cierre,total_sistema,total_declarado,diferencia,cantidad_pagos,cantidad_anulados,observacion,usuario,fecha_registro FROM prestamos.cierres_caja WHERE fecha=$1")){c.Parameters.AddWithValue(fecha);await using var r=await c.ExecuteReaderAsync();if(await r.ReadAsync()){id=r.GetInt32(0);total=r.GetDecimal(1);declared=r.GetDecimal(2);difference=r.GetDecimal(3);payments=r.GetInt32(4);annulled=r.GetInt32(5);note=r.IsDBNull(6)?null:r.GetString(6);user=r.GetString(7);created=r.GetDateTime(8);}}
  if(id is null){await using var c=source.CreateCommand("SELECT COALESCE(SUM(monto_pagado) FILTER(WHERE estado='APLICADO'),0),COUNT(*) FILTER(WHERE estado='APLICADO'),COUNT(*) FILTER(WHERE estado='ANULADO') FROM prestamos.pagos WHERE fecha_pago=$1");c.Parameters.AddWithValue(fecha);await using var r=await c.ExecuteReaderAsync();await r.ReadAsync();total=r.GetDecimal(0);payments=r.GetInt64(1);annulled=r.GetInt64(2);}
  var details=new List<CajaDetalleDto>();await using(var c=source.CreateCommand(id is null?"SELECT tp.nombre,COUNT(*),SUM(pg.monto_pagado) FROM prestamos.pagos pg JOIN prestamos.tipos_pago tp ON tp.id_tipo_pago=pg.id_tipo_pago WHERE pg.fecha_pago=$1 AND pg.estado='APLICADO' GROUP BY tp.nombre ORDER BY tp.nombre":"SELECT tipo_pago,cantidad,total FROM prestamos.cierre_caja_detalle WHERE id_cierre=$1 ORDER BY tipo_pago")){c.Parameters.AddWithValue((object?)id??fecha);await using var r=await c.ExecuteReaderAsync();while(await r.ReadAsync())details.Add(new(r.GetString(0),r.GetInt64(1),r.GetDecimal(2)));}
  var movements=new List<CajaMovimientoDto>();await using(var c=source.CreateCommand("""SELECT pg.id_pago,pg.id_prestamo,cl.nombre,tp.nombre,pg.monto_pagado,pg.estado,r.numero_recibo FROM prestamos.pagos pg JOIN prestamos.prestamos p ON p.id_prestamo=pg.id_prestamo JOIN prestamos.cliente cl ON cl.id_cliente=p.id_cliente JOIN prestamos.tipos_pago tp ON tp.id_tipo_pago=pg.id_tipo_pago LEFT JOIN prestamos.recibos_pago r ON r.id_pago=pg.id_pago WHERE pg.fecha_pago=$1 ORDER BY pg.id_pago DESC""")){c.Parameters.AddWithValue(fecha);await using var r=await c.ExecuteReaderAsync();while(await r.ReadAsync())movements.Add(new(r.GetInt32(0),r.GetInt32(1),r.GetString(2),r.GetString(3),r.GetDecimal(4),r.GetString(5),r.IsDBNull(6)?null:r.GetString(6)));}
  return new(id,fecha,id is not null,total,declared,difference,payments,annulled,note,user,created,details,movements);
 }
 public async Task<CajaDiaDto> CloseAsync(CerrarCajaRequest request,string usuario){await using var c=source.CreateCommand("SELECT prestamos.cerrar_caja($1,$2,$3,$4)");c.Parameters.AddWithValue(request.Fecha);c.Parameters.AddWithValue(request.TotalDeclarado);c.Parameters.AddWithValue((object?)request.Observacion??DBNull.Value);c.Parameters.AddWithValue(usuario);await c.ExecuteScalarAsync();return await DiaAsync(request.Fecha);}
 public async Task<List<CierreCajaListaDto>> HistoryAsync(){await using var c=source.CreateCommand("SELECT id_cierre,fecha,total_sistema,total_declarado,diferencia,cantidad_pagos,cantidad_anulados,usuario,fecha_registro FROM prestamos.cierres_caja ORDER BY fecha DESC LIMIT 100");var list=new List<CierreCajaListaDto>();await using var r=await c.ExecuteReaderAsync();while(await r.ReadAsync())list.Add(new(r.GetInt32(0),r.GetFieldValue<DateOnly>(1),r.GetDecimal(2),r.GetDecimal(3),r.GetDecimal(4),r.GetInt32(5),r.GetInt32(6),r.GetString(7),r.GetDateTime(8)));return list;}
}
