using QuestPDF.Fluent;using QuestPDF.Helpers;using QuestPDF.Infrastructure;
namespace SistemaPrestamos.Api.Services;
public sealed class CierreCajaPdfService(CierreCajaRepository repository)
{
 static string Money(decimal v)=>$"RD${v:N2}";
 public async Task<byte[]> GenerateAsync(DateOnly date){var d=await repository.DiaAsync(date);if(!d.Cerrada)throw new InvalidOperationException("La caja aún no está cerrada.");return Document.Create(doc=>doc.Page(page=>{page.Size(PageSizes.A4);page.Margin(34);page.DefaultTextStyle(x=>x.FontSize(9).FontColor("#26352E"));page.Header().Column(h=>{h.Item().Text("SAN & RÉDITO").FontSize(20).Bold().FontColor("#1F6A4D");h.Item().Text("COMPROBANTE DE CIERRE DE CAJA").FontSize(12).SemiBold();h.Item().Text($"Fecha operativa: {d.Fecha:dd/MM/yyyy} · Cierre #{d.Id:D5}").FontSize(8).FontColor("#78857E");});page.Content().PaddingVertical(20).Column(c=>{c.Spacing(14);c.Item().Row(r=>{Box(r,"Total del sistema",d.TotalSistema);Box(r,"Total declarado",d.TotalDeclarado??0);Box(r,"Diferencia",d.Diferencia??0,true);});c.Item().Text("Desglose de cobros").FontSize(12).Bold();c.Item().Table(t=>{t.ColumnsDefinition(x=>{x.RelativeColumn();x.ConstantColumn(80);x.ConstantColumn(120);});t.Header(h=>{Cell(h.Cell(),"TIPO DE PAGO",true);Cell(h.Cell(),"CANTIDAD",true,true);Cell(h.Cell(),"TOTAL",true,true);});foreach(var x in d.Detalle){Cell(t.Cell(),x.TipoPago.Replace('_',' '));Cell(t.Cell(),x.Cantidad.ToString(),false,true);Cell(t.Cell(),Money(x.Total),false,true);}if(d.Detalle.Count==0){Cell(t.Cell().ColumnSpan(3),"No se registraron cobros en esta fecha.");}});c.Item().Background("#F3F7F5").Padding(14).Column(x=>{x.Item().Text($"Pagos aplicados: {d.CantidadPagos} · Pagos anulados: {d.CantidadAnulados}").Bold();x.Item().PaddingTop(5).Text($"Cerrado por: {d.Usuario} · {d.FechaRegistro:dd/MM/yyyy hh:mm tt}").FontSize(8).FontColor("#68756E");if(!string.IsNullOrWhiteSpace(d.Observacion))x.Item().PaddingTop(7).Text($"Observación: {d.Observacion}").FontSize(8);});c.Item().PaddingTop(20).Row(r=>{r.RelativeItem().PaddingRight(20).Column(x=>{x.Item().LineHorizontal(1).LineColor("#AEB8B3");x.Item().AlignCenter().PaddingTop(5).Text("Responsable de caja").FontSize(7);});r.RelativeItem().PaddingLeft(20).Column(x=>{x.Item().LineHorizontal(1).LineColor("#AEB8B3");x.Item().AlignCenter().PaddingTop(5).Text("Supervisor").FontSize(7);});});});page.Footer().AlignCenter().Text("Documento de control interno · cierre inmutable").FontSize(7).FontColor("#89958F");})).GeneratePdf();}
 static void Box(RowDescriptor r,string label,decimal value,bool diff=false)=>r.RelativeItem().PaddingRight(8).Background(diff&&value!=0?"#FFF0ED":"#F3F7F5").Padding(13).Column(x=>{x.Item().Text(label).FontSize(7).FontColor("#78857E");x.Item().Text(Money(value)).FontSize(13).Bold().FontColor(diff&&value!=0?"#A64740":"#173F32");});
 static void Cell(IContainer c,string text,bool header=false,bool right=false){var x=c.BorderBottom(1).BorderColor("#E3E8E5").Padding(8);if(header)x=x.Background("#F3F7F5");var t=right?x.AlignRight().Text(text):x.Text(text);if(header)t.SemiBold().FontSize(7).FontColor("#65736C");}
}
