using System.Text.RegularExpressions;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
namespace SistemaPrestamos.Api.Services;
public sealed class ReciboPdfService(ReciboRepository repository,IWebHostEnvironment environment)
{
 public async Task<string> EnsureAsync(int id){var d=await repository.GetAsync(id)??throw new FileNotFoundException("Recibo no encontrado.");var safe=Regex.Replace(d.Cliente.Normalize(),@"[^\p{L}\p{N}-]+","-").Trim('-');var folder=Path.Combine(environment.ContentRootPath,"storage","recibos",$"{d.ClienteId:D5}-{safe}");Directory.CreateDirectory(folder);var path=Path.Combine(folder,$"{d.Numero}.pdf");
  Document.Create(doc=>doc.Page(page=>{page.Size(PageSizes.A5);page.Margin(34);page.DefaultTextStyle(x=>x.FontSize(10).FontColor("#26352E"));page.Header().Column(h=>{h.Item().Text("SAN & RÉDITO").FontSize(18).Bold().FontColor("#1F6A4D");h.Item().PaddingTop(4).Text("RECIBO DE PAGO").FontSize(9).SemiBold().FontColor("#77847D");});page.Content().PaddingVertical(24).Column(c=>{c.Spacing(12);if(d.EstadoPago=="ANULADO")c.Item().Background("#A64740").Padding(10).AlignCenter().Text("RECIBO ANULADO").Bold().FontColor(Colors.White);c.Item().Background("#F3F7F5").Padding(14).Row(r=>{r.RelativeItem().Column(x=>{x.Item().Text("Número de recibo").FontSize(8).FontColor("#78857E");x.Item().Text(d.Numero).Bold();});r.RelativeItem().AlignRight().Column(x=>{x.Item().AlignRight().Text("Fecha").FontSize(8).FontColor("#78857E");x.Item().AlignRight().Text(d.Fecha.ToString("dd/MM/yyyy")).Bold();});});c.Item().Text(d.Cliente).FontSize(15).Bold();if(!string.IsNullOrWhiteSpace(d.Telefono))c.Item().Text(d.Telefono).FontColor("#6E7A74");c.Item().LineHorizontal(1).LineColor("#E2E7E4");c.Item().Row(r=>{r.RelativeItem().Text("Préstamo");r.RelativeItem().AlignRight().Text($"PR-{d.PrestamoId:D5}").Bold();});c.Item().Row(r=>{r.RelativeItem().Text("Modalidad");r.RelativeItem().AlignRight().Text(d.TipoPrestamo).Bold();});c.Item().Row(r=>{r.RelativeItem().Text("Concepto");r.RelativeItem().AlignRight().Text(d.TipoPago.Replace('_',' ')).Bold();});c.Item().PaddingTop(3).Background("#F3F7F5").Padding(14).Column(x=>{x.Spacing(7);x.Item().Row(r=>{r.RelativeItem().Text("Monto prestado").FontColor("#6E7A74");r.RelativeItem().AlignRight().Text($"RD${d.MontoPrestado:N2}").Bold();});x.Item().Row(r=>{r.RelativeItem().Text("Pagado a la fecha").FontColor("#6E7A74");r.RelativeItem().AlignRight().Text($"RD${d.PagadoFecha:N2}").Bold();});x.Item().LineHorizontal(1).LineColor("#DDE5E1");x.Item().Row(r=>{r.RelativeItem().Text("Balance del préstamo").SemiBold();r.RelativeItem().AlignRight().Text($"RD${d.Balance:N2}").Bold().FontColor("#1F6A4D");});});c.Item().PaddingTop(4).Background(d.EstadoPago=="ANULADO"?"#725C59":"#173F32").Padding(16).Row(r=>{r.RelativeItem().Text("TOTAL RECIBIDO").FontColor(Colors.White);r.RelativeItem().AlignRight().Text($"RD${d.Monto:N2}").FontSize(16).Bold().FontColor(Colors.White);});if(d.EstadoPago=="ANULADO"&&!string.IsNullOrWhiteSpace(d.MotivoAnulacion))c.Item().Text($"Motivo de anulación: {d.MotivoAnulacion}").FontSize(8).FontColor("#A64740");if(!string.IsNullOrWhiteSpace(d.Observacion))c.Item().PaddingTop(8).Text($"Observación: {d.Observacion}").FontSize(8).FontColor("#77847D");});page.Footer().AlignCenter().Text("Gracias por su pago - Documento generado por el sistema").FontSize(7).FontColor("#89958F");})).GeneratePdf(path);await repository.SavePathAsync(id,path);return path;}
 public async Task<string> EnsureByPaymentAsync(int paymentId){var id=await repository.ReceiptIdByPaymentAsync(paymentId)??throw new FileNotFoundException("Recibo no encontrado.");return await EnsureAsync(id);}
}
