using Npgsql;
namespace SistemaPrestamos.Api.Services;
public sealed record ClienteRecibosDto(int ClienteId,string Cliente,string? Telefono,int Cantidad,DateOnly UltimoPago,decimal TotalPagado);
public sealed record ReciboListaDto(int Id,int PagoId,string Numero,int PrestamoId,string TipoPago,DateOnly Fecha,decimal Monto,string Estado,string? MotivoAnulacion,bool PuedeAnular,string? RutaPdf);
public sealed record ReciboDatosDto(int Id,string Numero,int ClienteId,string Cliente,string? Telefono,int PrestamoId,string TipoPrestamo,string TipoPago,DateOnly Fecha,decimal Monto,decimal MontoPrestado,decimal PagadoFecha,decimal Balance,string EstadoPago,string? MotivoAnulacion,string? Observacion,string? RutaPdf);
public sealed class ReciboRepository(NpgsqlDataSource source)
{
 public async Task<List<ClienteRecibosDto>> ClientsAsync(){await using var c=source.CreateCommand("""SELECT c.id_cliente,c.nombre,c.telefono,COUNT(r.id_recibo),MAX(pg.fecha_pago),COALESCE(SUM(pg.monto_pagado) FILTER(WHERE pg.estado='APLICADO'),0) FROM prestamos.recibos_pago r JOIN prestamos.pagos pg ON pg.id_pago=r.id_pago JOIN prestamos.prestamos p ON p.id_prestamo=pg.id_prestamo JOIN prestamos.cliente c ON c.id_cliente=p.id_cliente GROUP BY c.id_cliente,c.nombre,c.telefono ORDER BY c.nombre""");var l=new List<ClienteRecibosDto>();await using var x=await c.ExecuteReaderAsync();while(await x.ReadAsync())l.Add(new(x.GetInt32(0),x.GetString(1),x.IsDBNull(2)?null:x.GetString(2),checked((int)x.GetInt64(3)),x.GetFieldValue<DateOnly>(4),x.GetDecimal(5)));return l;}
 public async Task<List<ReciboListaDto>> ByClientAsync(int id){await using var c=source.CreateCommand("""SELECT r.id_recibo,pg.id_pago,r.numero_recibo,p.id_prestamo,tp.nombre,pg.fecha_pago,pg.monto_pagado,pg.estado,pg.motivo_anulacion,pg.estado='APLICADO' AND pg.id_pago=(SELECT max(x.id_pago) FROM prestamos.pagos x WHERE x.id_prestamo=pg.id_prestamo AND x.estado='APLICADO'),r.ruta_pdf FROM prestamos.recibos_pago r JOIN prestamos.pagos pg ON pg.id_pago=r.id_pago JOIN prestamos.prestamos p ON p.id_prestamo=pg.id_prestamo JOIN prestamos.tipos_pago tp ON tp.id_tipo_pago=pg.id_tipo_pago WHERE p.id_cliente=$1 ORDER BY pg.fecha_pago DESC,r.id_recibo DESC""");c.Parameters.AddWithValue(id);var l=new List<ReciboListaDto>();await using var x=await c.ExecuteReaderAsync();while(await x.ReadAsync())l.Add(new(x.GetInt32(0),x.GetInt32(1),x.GetString(2),x.GetInt32(3),x.GetString(4),x.GetFieldValue<DateOnly>(5),x.GetDecimal(6),x.GetString(7),x.IsDBNull(8)?null:x.GetString(8),x.GetBoolean(9),x.IsDBNull(10)?null:x.GetString(10)));return l;}
 public async Task<ReciboDatosDto?> GetAsync(int id){await using var c=source.CreateCommand("""
  SELECT r.id_recibo,r.numero_recibo,c.id_cliente,c.nombre,c.telefono,p.id_prestamo,tpr.nombre,tp.nombre,
         pg.fecha_pago,pg.monto_pagado,p.monto_prestado,
         CASE WHEN tpr.nombre='SAN' THEN COALESCE((SELECT SUM(px.monto_pagado) FROM prestamos.pagos px WHERE px.id_prestamo=p.id_prestamo AND px.id_pago<=pg.id_pago AND (px.estado='APLICADO' OR px.id_pago=pg.id_pago)),0)
              ELSE COALESCE((SELECT SUM(dp.monto) FROM prestamos.pagos px JOIN prestamos.detalle_pagos dp ON dp.id_pago=px.id_pago WHERE px.id_prestamo=p.id_prestamo AND px.id_pago<=pg.id_pago AND (px.estado='APLICADO' OR px.id_pago=pg.id_pago) AND dp.concepto='CAPITAL'),0) END AS pagado_fecha,
         GREATEST(0,CASE WHEN tpr.nombre='SAN' THEN COALESCE(p.total_a_pagar,p.monto_prestado)-COALESCE((SELECT SUM(px.monto_pagado) FROM prestamos.pagos px WHERE px.id_prestamo=p.id_prestamo AND px.id_pago<=pg.id_pago AND (px.estado='APLICADO' OR px.id_pago=pg.id_pago)),0)
                         ELSE p.monto_prestado-COALESCE((SELECT SUM(dp.monto) FROM prestamos.pagos px JOIN prestamos.detalle_pagos dp ON dp.id_pago=px.id_pago WHERE px.id_prestamo=p.id_prestamo AND px.id_pago<=pg.id_pago AND (px.estado='APLICADO' OR px.id_pago=pg.id_pago) AND dp.concepto='CAPITAL'),0) END) AS balance,
         pg.estado,pg.motivo_anulacion,pg.observacion,r.ruta_pdf
  FROM prestamos.recibos_pago r JOIN prestamos.pagos pg ON pg.id_pago=r.id_pago JOIN prestamos.prestamos p ON p.id_prestamo=pg.id_prestamo
  JOIN prestamos.cliente c ON c.id_cliente=p.id_cliente JOIN prestamos.tipos_prestamo tpr ON tpr.id_tipo_prestamos=p.id_tipo_prestamos
  JOIN prestamos.tipos_pago tp ON tp.id_tipo_pago=pg.id_tipo_pago WHERE r.id_recibo=$1
  """);c.Parameters.AddWithValue(id);await using var x=await c.ExecuteReaderAsync();return await x.ReadAsync()?new(x.GetInt32(0),x.GetString(1),x.GetInt32(2),x.GetString(3),x.IsDBNull(4)?null:x.GetString(4),x.GetInt32(5),x.GetString(6),x.GetString(7),x.GetFieldValue<DateOnly>(8),x.GetDecimal(9),x.GetDecimal(10),x.GetDecimal(11),x.GetDecimal(12),x.GetString(13),x.IsDBNull(14)?null:x.GetString(14),x.IsDBNull(15)?null:x.GetString(15),x.IsDBNull(16)?null:x.GetString(16)):null;}
 public async Task<int?> ReceiptIdByPaymentAsync(int paymentId){await using var c=source.CreateCommand("SELECT id_recibo FROM prestamos.recibos_pago WHERE id_pago=$1");c.Parameters.AddWithValue(paymentId);var v=await c.ExecuteScalarAsync();return v is null?null:(int)v;}
 public async Task SavePathAsync(int id,string path){await using var c=source.CreateCommand("UPDATE prestamos.recibos_pago SET ruta_pdf=$2,estado=CASE WHEN estado='ANULADO' THEN estado ELSE 'PDF_GENERADO' END WHERE id_recibo=$1");c.Parameters.AddWithValue(id);c.Parameters.AddWithValue(path);await c.ExecuteNonQueryAsync();}
}
