using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
namespace SistemaPrestamos.Api.Services;

public sealed class ReportePdfService(ReporteRepository repository)
{
 static string Money(decimal value)=>$"RD${value:N2}";
 static void Header(IContainer c,string title,string subtitle)=>c.Column(x=>{x.Item().Text("SAN & RÉDITO").FontSize(20).Bold().FontColor("#1F6A4D");x.Item().Text(title).FontSize(15).SemiBold();x.Item().Text(subtitle).FontSize(8).FontColor("#78857E");});
 public async Task<byte[]> CarteraAsync(){var d=await repository.CarteraAsync();return Document.Create(doc=>doc.Page(page=>{page.Size(PageSizes.A4.Landscape());page.Margin(28);page.DefaultTextStyle(x=>x.FontSize(8).FontColor("#26352E"));page.Header().Element(x=>Header(x,"Cartera general",$"Generado el {DateTime.Today:dd/MM/yyyy}"));page.Content().PaddingVertical(16).Column(c=>{c.Spacing(12);c.Item().Row(r=>{Summary(r,"Prestado",d.TotalPrestado);Summary(r,"Pagado / abonado",d.TotalPagado);Summary(r,"Balance",d.TotalBalance);Summary(r,"Vencido",d.TotalVencido,true);});c.Item().Table(t=>{t.ColumnsDefinition(x=>{x.ConstantColumn(58);x.RelativeColumn(2.2f);x.ConstantColumn(55);x.ConstantColumn(65);x.RelativeColumn();x.RelativeColumn();x.RelativeColumn();x.RelativeColumn();});t.Header(h=>{Cell(h.Cell(),"PRÉSTAMO",true);Cell(h.Cell(),"CLIENTE",true);Cell(h.Cell(),"TIPO",true);Cell(h.Cell(),"ESTADO",true);Cell(h.Cell(),"PRESTADO",true);Cell(h.Cell(),"PAGADO",true);Cell(h.Cell(),"BALANCE",true);Cell(h.Cell(),"VENCIDO",true);});foreach(var x in d.Prestamos){Cell(t.Cell(),$"PR-{x.PrestamoId:D5}");Cell(t.Cell(),x.Cliente);Cell(t.Cell(),x.Tipo);Cell(t.Cell(),x.Estado);Cell(t.Cell(),Money(x.MontoPrestado),align:true);Cell(t.Cell(),Money(x.Pagado),align:true);Cell(t.Cell(),Money(x.Balance),align:true);Cell(t.Cell(),x.Vencido>0?$"{Money(x.Vencido)} · {x.DiasAtraso}d":"—",align:true);}});});page.Footer().AlignCenter().Text(x=>{x.Span("Página ");x.CurrentPageNumber();x.Span(" de ");x.TotalPages();});})).GeneratePdf();}
 public async Task<byte[]> EstadoCuentaAsync(int id){var d=await repository.EstadoCuentaAsync(id)??throw new FileNotFoundException();return Document.Create(doc=>doc.Page(page=>{page.Size(PageSizes.A4);page.Margin(32);page.DefaultTextStyle(x=>x.FontSize(9).FontColor("#26352E"));page.Header().Element(x=>Header(x,"Estado de cuenta",$"Cliente #{d.Cliente.Id:D4} · corte {DateTime.Today:dd/MM/yyyy}"));page.Content().PaddingVertical(16).Column(c=>{c.Spacing(14);c.Item().Background("#F3F7F5").Padding(14).Column(x=>{x.Item().Text(d.Cliente.Nombre).FontSize(15).Bold();x.Item().Text(string.Join(" · ",new[]{d.Cliente.Documento,d.Cliente.Telefono}.Where(v=>!string.IsNullOrWhiteSpace(v)))).FontColor("#6E7A74");if(!string.IsNullOrWhiteSpace(d.Cliente.Direccion))x.Item().Text(d.Cliente.Direccion).FontSize(8).FontColor("#77847D");});c.Item().Row(r=>{Summary(r,"Total prestado",d.TotalPrestado);Summary(r,"Pagado / abonado",d.TotalPagado);Summary(r,"Balance actual",d.Balance,true);});c.Item().Text("Préstamos").FontSize(12).Bold();c.Item().Table(t=>{t.ColumnsDefinition(x=>{x.ConstantColumn(60);x.ConstantColumn(55);x.ConstantColumn(65);x.RelativeColumn();x.RelativeColumn();x.RelativeColumn();});t.Header(h=>{Cell(h.Cell(),"PRÉSTAMO",true);Cell(h.Cell(),"TIPO",true);Cell(h.Cell(),"ESTADO",true);Cell(h.Cell(),"PRESTADO",true);Cell(h.Cell(),"PAGADO",true);Cell(h.Cell(),"BALANCE",true);});foreach(var x in d.Prestamos){Cell(t.Cell(),$"PR-{x.PrestamoId:D5}");Cell(t.Cell(),x.Tipo);Cell(t.Cell(),x.Estado);Cell(t.Cell(),Money(x.MontoPrestado),align:true);Cell(t.Cell(),Money(x.Pagado),align:true);Cell(t.Cell(),Money(x.Balance),align:true);}});c.Item().Text("Historial de pagos").FontSize(12).Bold();if(d.Movimientos.Count==0)c.Item().Text("No hay pagos registrados.").FontColor("#78857E");else c.Item().Table(t=>{t.ColumnsDefinition(x=>{x.ConstantColumn(55);x.ConstantColumn(60);x.RelativeColumn();x.RelativeColumn();x.ConstantColumn(65);});t.Header(h=>{Cell(h.Cell(),"FECHA",true);Cell(h.Cell(),"PRÉSTAMO",true);Cell(h.Cell(),"CONCEPTO",true);Cell(h.Cell(),"MONTO",true);Cell(h.Cell(),"ESTADO",true);});foreach(var x in d.Movimientos){Cell(t.Cell(),x.Fecha.ToString("dd/MM/yy"));Cell(t.Cell(),$"PR-{x.PrestamoId:D5}");Cell(t.Cell(),x.Concepto.Replace('_',' '));Cell(t.Cell(),Money(x.Monto),align:true);Cell(t.Cell(),x.Estado);}});});page.Footer().AlignCenter().Text(x=>{x.Span("Documento informativo · Página ");x.CurrentPageNumber();x.Span(" de ");x.TotalPages();});})).GeneratePdf();}
 static void Summary(RowDescriptor r,string label,decimal value,bool alert=false)=>r.RelativeItem().PaddingRight(8).Background(alert?"#FFF2EE":"#F3F7F5").Padding(11).Column(x=>{x.Item().Text(label).FontSize(7).FontColor("#78857E");x.Item().Text(Money(value)).FontSize(12).Bold().FontColor(alert?"#A64740":"#173F32");});
 static void Cell(IContainer c,string text,bool header=false,bool align=false){var x=c.BorderBottom(1).BorderColor("#E3E8E5").PaddingVertical(7).PaddingHorizontal(5);if(header)x=x.Background("#F3F7F5");var t=align?x.AlignRight().Text(text):x.Text(text);if(header)t.SemiBold().FontSize(7).FontColor("#65736C");}
}
