using Npgsql;
namespace SistemaPrestamos.Api.Services;
public sealed record UsuarioDto(int Id,string Nombre,string Usuario,string Rol,string Estado,DateTime FechaRegistro,DateTime? UltimoAcceso);
public sealed record CrearUsuarioRequest(string Nombre,string Usuario,string Clave,string Rol);
public sealed record ActualizarUsuarioRequest(string Nombre,string Rol,string Estado);
public sealed record CambiarClaveUsuarioRequest(string Clave);
public sealed class UsuarioRepository(NpgsqlDataSource source,PasswordService passwords)
{
 public async Task<List<UsuarioDto>> ListAsync(){await using var c=source.CreateCommand("SELECT id_usuario,nombre,usuario,rol,estado,fecha_registro,ultimo_acceso FROM prestamos.usuarios ORDER BY nombre");var list=new List<UsuarioDto>();await using var r=await c.ExecuteReaderAsync();while(await r.ReadAsync())list.Add(new(r.GetInt32(0),r.GetString(1),r.GetString(2),r.GetString(3),r.GetString(4),r.GetDateTime(5),r.IsDBNull(6)?null:r.GetDateTime(6)));return list;}
 public async Task<int> CreateAsync(CrearUsuarioRequest q,int actor){var role=ValidateRole(q.Rol);if(string.IsNullOrWhiteSpace(q.Nombre)||string.IsNullOrWhiteSpace(q.Usuario))throw new ArgumentException("Nombre y usuario son obligatorios.");if(q.Clave.Length<10)throw new ArgumentException("La contraseña debe tener al menos 10 caracteres.");await using var cn=await source.OpenConnectionAsync();await using var tx=await cn.BeginTransactionAsync();await using var c=new NpgsqlCommand("INSERT INTO prestamos.usuarios(nombre,usuario,clave_hash,rol,estado) VALUES($1,$2,$3,$4,'ACTIVO') RETURNING id_usuario",cn,tx);c.Parameters.AddWithValue(q.Nombre.Trim());c.Parameters.AddWithValue(q.Usuario.Trim());c.Parameters.AddWithValue(passwords.Hash(q.Clave));c.Parameters.AddWithValue(role);var id=(int)(await c.ExecuteScalarAsync())!;await Audit(cn,tx,id,"CREADO",$"Rol inicial: {role}",actor);await tx.CommitAsync();return id;}
 public async Task UpdateAsync(int id,ActualizarUsuarioRequest q,int actor){var role=ValidateRole(q.Rol);var state=q.Estado.Trim().ToUpperInvariant();if(state is not("ACTIVO" or "INACTIVO"))throw new ArgumentException("Estado de usuario inválido.");if(string.IsNullOrWhiteSpace(q.Nombre))throw new ArgumentException("El nombre es obligatorio.");await using var cn=await source.OpenConnectionAsync();await using var tx=await cn.BeginTransactionAsync();string oldRole,oldState;await using(var read=new NpgsqlCommand("SELECT rol,estado FROM prestamos.usuarios WHERE id_usuario=$1 FOR UPDATE",cn,tx)){read.Parameters.AddWithValue(id);await using var r=await read.ExecuteReaderAsync();if(!await r.ReadAsync())throw new KeyNotFoundException();oldRole=r.GetString(0);oldState=r.GetString(1);}if(id==actor&&state=="INACTIVO")throw new ArgumentException("No puede desactivar su propia cuenta.");if(oldRole=="ADMIN"&&oldState=="ACTIVO"&&(role!="ADMIN"||state!="ACTIVO")){await using var count=new NpgsqlCommand("SELECT COUNT(*) FROM prestamos.usuarios WHERE rol='ADMIN' AND estado='ACTIVO'",cn,tx);if((long)(await count.ExecuteScalarAsync())!<=1)throw new ArgumentException("Debe conservar al menos un administrador activo.");}await using(var update=new NpgsqlCommand("UPDATE prestamos.usuarios SET nombre=$2,rol=$3,estado=$4 WHERE id_usuario=$1",cn,tx)){update.Parameters.AddWithValue(id);update.Parameters.AddWithValue(q.Nombre.Trim());update.Parameters.AddWithValue(role);update.Parameters.AddWithValue(state);await update.ExecuteNonQueryAsync();}await Audit(cn,tx,id,"ACTUALIZADO",$"Rol {oldRole} → {role}; estado {oldState} → {state}",actor);await tx.CommitAsync();}
 public async Task ResetPasswordAsync(int id,string password,int actor){if(password.Length<10)throw new ArgumentException("La contraseña debe tener al menos 10 caracteres.");await using var cn=await source.OpenConnectionAsync();await using var tx=await cn.BeginTransactionAsync();await using(var c=new NpgsqlCommand("UPDATE prestamos.usuarios SET clave_hash=$2 WHERE id_usuario=$1",cn,tx)){c.Parameters.AddWithValue(id);c.Parameters.AddWithValue(passwords.Hash(password));if(await c.ExecuteNonQueryAsync()==0)throw new KeyNotFoundException();}await Audit(cn,tx,id,"CLAVE_RESTABLECIDA",null,actor);await tx.CommitAsync();}
 static string ValidateRole(string role){var value=role.Trim().ToUpperInvariant();return value is "ADMIN" or "COBRADOR" or "CONSULTA"?value:throw new ArgumentException("Rol de usuario inválido.");}
 static async Task Audit(NpgsqlConnection cn,NpgsqlTransaction tx,int id,string action,string? detail,int actor){await using var c=new NpgsqlCommand("INSERT INTO prestamos.auditoria_usuarios(id_usuario,accion,detalle,realizado_por) VALUES($1,$2,$3,$4)",cn,tx);c.Parameters.AddWithValue(id);c.Parameters.AddWithValue(action);c.Parameters.AddWithValue((object?)detail??DBNull.Value);c.Parameters.AddWithValue(actor);await c.ExecuteNonQueryAsync();}
}
