BEGIN;
CREATE TABLE IF NOT EXISTS prestamos.cierres_caja(
 id_cierre integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 fecha date NOT NULL UNIQUE,
 total_sistema numeric(14,2) NOT NULL,
 total_declarado numeric(14,2) NOT NULL,
 diferencia numeric(14,2) NOT NULL,
 cantidad_pagos integer NOT NULL,
 cantidad_anulados integer NOT NULL,
 observacion text,
 usuario varchar(120) NOT NULL,
 fecha_registro timestamp without time zone NOT NULL DEFAULT current_timestamp,
 CONSTRAINT ck_cierre_totales CHECK(total_sistema>=0 AND total_declarado>=0)
);
CREATE TABLE IF NOT EXISTS prestamos.cierre_caja_detalle(
 id_detalle integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 id_cierre integer NOT NULL REFERENCES prestamos.cierres_caja(id_cierre),
 tipo_pago varchar(40) NOT NULL,
 cantidad integer NOT NULL,
 total numeric(14,2) NOT NULL,
 UNIQUE(id_cierre,tipo_pago)
);

CREATE OR REPLACE FUNCTION prestamos.cerrar_caja(p_fecha date,p_total_declarado numeric,p_observacion text,p_usuario varchar)
RETURNS integer LANGUAGE plpgsql AS $$
DECLARE v_id integer;v_total numeric;v_pagos integer;v_anulados integer;
BEGIN
 IF p_fecha>current_date THEN RAISE EXCEPTION 'No puede cerrar una fecha futura.';END IF;
 IF p_total_declarado<0 THEN RAISE EXCEPTION 'El total declarado no puede ser negativo.';END IF;
 PERFORM pg_advisory_xact_lock(hashtext('cierre-caja-'||p_fecha::text));
 IF EXISTS(SELECT 1 FROM prestamos.cierres_caja WHERE fecha=p_fecha) THEN RAISE EXCEPTION 'La caja de esta fecha ya está cerrada.';END IF;
 SELECT COALESCE(SUM(monto_pagado) FILTER(WHERE estado='APLICADO'),0),COUNT(*) FILTER(WHERE estado='APLICADO'),COUNT(*) FILTER(WHERE estado='ANULADO') INTO v_total,v_pagos,v_anulados FROM prestamos.pagos WHERE fecha_pago=p_fecha;
 INSERT INTO prestamos.cierres_caja(fecha,total_sistema,total_declarado,diferencia,cantidad_pagos,cantidad_anulados,observacion,usuario)
 VALUES(p_fecha,v_total,p_total_declarado,p_total_declarado-v_total,v_pagos,v_anulados,NULLIF(trim(coalesce(p_observacion,'')),''),left(coalesce(p_usuario,'Sistema'),120)) RETURNING id_cierre INTO v_id;
 INSERT INTO prestamos.cierre_caja_detalle(id_cierre,tipo_pago,cantidad,total)
 SELECT v_id,tp.nombre,COUNT(*),SUM(pg.monto_pagado) FROM prestamos.pagos pg JOIN prestamos.tipos_pago tp ON tp.id_tipo_pago=pg.id_tipo_pago WHERE pg.fecha_pago=p_fecha AND pg.estado='APLICADO' GROUP BY tp.nombre;
 RETURN v_id;
END $$;

CREATE OR REPLACE FUNCTION prestamos.fn_bloquear_fecha_cerrada() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
 IF EXISTS(SELECT 1 FROM prestamos.cierres_caja WHERE fecha=NEW.fecha_pago) THEN
   RAISE EXCEPTION 'La caja del % está cerrada; no se permiten nuevos movimientos ni anulaciones.',to_char(NEW.fecha_pago,'DD/MM/YYYY');
 END IF;
 RETURN NEW;
END $$;
DROP TRIGGER IF EXISTS trg_bloquear_fecha_cerrada ON prestamos.pagos;
CREATE TRIGGER trg_bloquear_fecha_cerrada BEFORE INSERT OR UPDATE OF fecha_pago,estado ON prestamos.pagos FOR EACH ROW EXECUTE FUNCTION prestamos.fn_bloquear_fecha_cerrada();
COMMIT;
