BEGIN;
UPDATE prestamos.usuarios SET rol='ADMIN' WHERE rol IS NULL OR rol NOT IN('ADMIN','COBRADOR','CONSULTA');
UPDATE prestamos.usuarios SET estado='ACTIVO' WHERE estado IS NULL OR estado NOT IN('ACTIVO','INACTIVO');
ALTER TABLE prestamos.usuarios ALTER COLUMN rol SET NOT NULL,ALTER COLUMN estado SET NOT NULL;
ALTER TABLE prestamos.usuarios ADD COLUMN IF NOT EXISTS ultimo_acceso timestamp without time zone;
DO $$ BEGIN IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conname='ck_usuarios_rol') THEN ALTER TABLE prestamos.usuarios ADD CONSTRAINT ck_usuarios_rol CHECK(rol IN('ADMIN','COBRADOR','CONSULTA'));END IF;IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conname='ck_usuarios_estado') THEN ALTER TABLE prestamos.usuarios ADD CONSTRAINT ck_usuarios_estado CHECK(estado IN('ACTIVO','INACTIVO'));END IF;END $$;
CREATE TABLE IF NOT EXISTS prestamos.auditoria_usuarios(
 id_auditoria integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 id_usuario integer NOT NULL REFERENCES prestamos.usuarios(id_usuario),
 accion varchar(40) NOT NULL,
 detalle text,
 realizado_por integer REFERENCES prestamos.usuarios(id_usuario),
 fecha timestamp without time zone NOT NULL DEFAULT current_timestamp
);
COMMIT;
