import{useEffect,useMemo,useState}from'react'
import'./ReportesView.css'
const API=import.meta.env.VITE_API_URL??'http://localhost:5159'
type Cliente={id:number;nombre:string;telefono?:string}
type Fila={prestamoId:number;clienteId:number;cliente:string;tipo:string;estado:string;montoPrestado:number;pagado:number;balance:number;vencido:number;diasAtraso:number}
type Cartera={totalPrestado:number;totalPagado:number;totalBalance:number;totalVencido:number;prestamos:Fila[]}
type Estado={cliente:{id:number;nombre:string;documento?:string;telefono?:string};totalPrestado:number;totalPagado:number;balance:number;prestamos:Fila[];movimientos:unknown[]}
const money=(v=0)=>new Intl.NumberFormat('es-DO',{style:'currency',currency:'DOP'}).format(v)
async function req(path:string,token:string){const r=await fetch(`${API}${path}`,{headers:{Authorization:`Bearer ${token}`}});if(!r.ok)throw new Error('No fue posible generar el reporte.');return r.json()}
export default function ReportesView({token,clientes}:{token:string;clientes:Cliente[]}){
 const[cartera,setCartera]=useState<Cartera|null>(null),[clienteId,setClienteId]=useState(0),[estado,setEstado]=useState<Estado|null>(null),[search,setSearch]=useState(''),[filter,setFilter]=useState('TODOS'),[error,setError]=useState(''),[opening,setOpening]=useState('')
 useEffect(()=>{req('/api/reportes/cartera',token).then(setCartera).catch(e=>setError(e.message))},[token])
 useEffect(()=>{if(!clienteId){setEstado(null);return}req(`/api/reportes/clientes/${clienteId}/estado-cuenta`,token).then(setEstado).catch(e=>setError(e.message))},[clienteId,token])
 const rows=useMemo(()=>{const q=search.trim().toLowerCase();return(cartera?.prestamos??[]).filter(x=>(filter==='TODOS'||x.estado===filter)&&(!q||`${x.cliente} ${x.prestamoId} ${x.tipo}`.toLowerCase().includes(q)))},[cartera,search,filter])
 async function openPdf(path:string,key:string){setOpening(key);setError('');try{const r=await fetch(`${API}${path}`,{headers:{Authorization:`Bearer ${token}`}});if(!r.ok)throw new Error('No fue posible abrir el PDF.');const url=URL.createObjectURL(await r.blob());window.open(url,'_blank','noopener,noreferrer');setTimeout(()=>URL.revokeObjectURL(url),120000)}catch(e){setError((e as Error).message)}finally{setOpening('')}}
 return <section className="reports-page">{error&&<div className="inline-error">{error}<button onClick={()=>setError('')}>×</button></div>}<div className="report-hero"><div><p className="eyebrow">INFORMACIÓN FINANCIERA</p><h2>Reportes claros para tomar decisiones</h2><p>Consulte la cartera completa o prepare el estado de cuenta de un cliente.</p></div><button onClick={()=>openPdf('/api/reportes/cartera/pdf','cartera')} disabled={opening==='cartera'}>{opening==='cartera'?'Generando…':'Descargar cartera PDF'}</button></div>{cartera&&<><div className="report-totals"><article><span>Total prestado</span><b>{money(cartera.totalPrestado)}</b></article><article><span>Pagado / abonado</span><b>{money(cartera.totalPagado)}</b></article><article><span>Balance actual</span><b>{money(cartera.totalBalance)}</b></article><article className={cartera.totalVencido>0?'report-alert':''}><span>Total vencido</span><b>{money(cartera.totalVencido)}</b></article></div><section className="report-card statement-builder"><div><span>ESTADO DE CUENTA</span><h3>Seleccione un cliente</h3><p>El documento incluye sus préstamos, balances e historial de pagos.</p></div><select value={clienteId||''} onChange={e=>setClienteId(Number(e.target.value))}><option value="">Buscar cliente</option>{clientes.map(c=><option value={c.id} key={c.id}>{c.nombre} · #{String(c.id).padStart(4,'0')}</option>)}</select>{estado&&<div className="statement-preview"><div><small>Cliente</small><b>{estado.cliente.nombre}</b></div><div><small>Préstamos</small><b>{estado.prestamos.length}</b></div><div><small>Balance</small><b>{money(estado.balance)}</b></div><button onClick={()=>openPdf(`/api/reportes/clientes/${clienteId}/estado-cuenta/pdf`,'estado')} disabled={opening==='estado'}>{opening==='estado'?'Generando…':'Ver estado de cuenta'}</button></div>}</section><section className="report-card portfolio-report"><div className="report-card-head"><div><span>DETALLE DE CARTERA</span><h3>{rows.length} préstamos</h3></div><div className="report-controls"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar cliente o préstamo"/><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="TODOS">Todos los estados</option><option>ACTIVO</option><option>SALDADO</option><option>ATRASADO</option><option>REENGANCHADO</option></select></div></div><div className="table-wrap"><table><thead><tr><th>Préstamo</th><th>Cliente</th><th>Tipo</th><th>Estado</th><th>Prestado</th><th>Balance</th><th>Vencido</th></tr></thead><tbody>{rows.map(x=><tr key={x.prestamoId}><td>PR-{String(x.prestamoId).padStart(5,'0')}</td><td><b>{x.cliente}</b></td><td>{x.tipo}</td><td><span className={`report-status ${x.estado.toLowerCase()}`}>{x.estado}</span></td><td>{money(x.montoPrestado)}</td><td><b>{money(x.balance)}</b></td><td className={x.vencido>0?'overdue-value':''}>{x.vencido>0?`${money(x.vencido)} · ${x.diasAtraso}d`:'—'}</td></tr>)}</tbody></table></div></section></>}</section>
}
